// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv1vPRZ443Ua8USKgZfe93DGTugixuCd0',
    appId: '1:228685104107:web:3be84c45154841eb254fae',
    messagingSenderId: '228685104107',
    projectId: 'freecycle-corner',
    authDomain: 'freecycle-corner.firebaseapp.com',
    storageBucket: 'freecycle-corner.firebasestorage.app',
    measurementId: 'G-H40S7YTZ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyVOJxHsSlw2fWwb1nJdPpbL6zvkUMe3Q',
    appId: '1:228685104107:android:5707d3d1acf26b0b254fae',
    messagingSenderId: '228685104107',
    projectId: 'freecycle-corner',
    storageBucket: 'freecycle-corner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2WAjKDqlLhnFui06KHa9UZVJyTGs2kX4',
    appId: '1:228685104107:ios:327d0029b01ae802254fae',
    messagingSenderId: '228685104107',
    projectId: 'freecycle-corner',
    storageBucket: 'freecycle-corner.firebasestorage.app',
    iosBundleId: 'com.example.freecycleCorner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2WAjKDqlLhnFui06KHa9UZVJyTGs2kX4',
    appId: '1:228685104107:ios:327d0029b01ae802254fae',
    messagingSenderId: '228685104107',
    projectId: 'freecycle-corner',
    storageBucket: 'freecycle-corner.firebasestorage.app',
    iosBundleId: 'com.example.freecycleCorner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv1vPRZ443Ua8USKgZfe93DGTugixuCd0',
    appId: '1:228685104107:web:982c59d54e04acdd254fae',
    messagingSenderId: '228685104107',
    projectId: 'freecycle-corner',
    authDomain: 'freecycle-corner.firebaseapp.com',
    storageBucket: 'freecycle-corner.firebasestorage.app',
    measurementId: 'G-R8ZGTHN40Z',
  );
}
